### ISSUE TITLE
[ERROR] The overall architecture image in overview.md is broken because of an unexpected image file extension change in 0.5.0

### ISSUE THREAD

**Issue by yamasite** [milvus-io/docs#110]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Where is the error**
The error exists in both English and Chinese version of overview.md. You can also see the error in the website:
https://milvus.io/docs/zh-CN/aboutmilvus/overview/
https://milvus.io/docs/en/aboutmilvus/overview/

**What caused the error**
The image name was milvus_arch.png in branch 0.4.0 but became milvus_arch.jpg in branch 0.5.0.

![image](https://user-images.githubusercontent.com/10089260/67221484-1c468e80-f45e-11e9-9420-fb4aad8b80b7.png)

![image](https://user-images.githubusercontent.com/10089260/67221367-e7d2d280-f45d-11e9-8ba5-6c7ee7db6416.png)

**How would you like to improve it**
Fix the broken link by updating the file extension to png.

**Screenshots**

![image](https://user-images.githubusercontent.com/10089260/67220874-22883b00-f45d-11e9-83e4-c2c57d591fb4.png)
![image](https://user-images.githubusercontent.com/10089260/67220911-2f0c9380-f45d-11e9-95b0-f21208518892.png)

**Comment by JinHai-CN** [comment]
Yes, the link is broken!

**Comment by yamasite** [comment]
Done.
