### ISSUE TITLE
我现在现有镜像下 构建这个工具怎么操作

### ISSUE THREAD

**Issue by Jie-Yuan** [milvus-io/docs#124]
我现在现有镜像下 构建这个工具怎么操作

**Comment by jielinxu** [comment]
请问你是想知道如何使用我们的产品，还是想用源码打包 Docker 镜像？如果你有更多关于 Milvus 的问题，请移步至 [milvus repo](https://github.com/milvus-io/milvus)，或 [加入我们的社区](https://join.slack.com/t/milvusio/shared_invite/enQtNzY1OTQ0NDI3NjMzLWNmYmM1NmNjOTQ5MGI5NDhhYmRhMGU5M2NhNzhhMDMzY2MzNDdlYjM5ODQ5MmE3ODFlYzU3YjJkNmVlNDQ2ZTk)，非常感谢！

**Comment by JinHai-CN** [comment]
@Jie-Yuan 欢迎加入Slack，沟通 :D

**Comment by Jie-Yuan** [comment]
> 请问你是想知道如何使用我们的产品，还是想用源码打包 Docker 镜像？如果你有更多关于 Milvus 的问题，请移步至 [milvus repo](https://github.com/milvus-io/milvus)，或 [加入我们的社区](https://join.slack.com/t/milvusio/shared_invite/enQtNzY1OTQ0NDI3NjMzLWNmYmM1NmNjOTQ5MGI5NDhhYmRhMGU5M2NhNzhhMDMzY2MzNDdlYjM5ODQ5MmE3ODFlYzU3YjJkNmVlNDQ2ZTk)，非常感谢！

对的，我想自定义自己的镜像

**Comment by ZhifengZhang-CN** [comment]
@Jie-Yuan 在[milvus repo](https://github.com/milvus-io/milvus)中的docker/deploy目录下有构建docker image的Dockerfile，可自定义镜像。
