### ISSUE TITLE
[Suggestion] some enhancement on docs

### ISSUE THREAD

**Issue by ReigenAraka** [milvus-io/docs#141]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

i think there has some enhancements in [Install milvus]

**Describe your suggestion**
1.change multi line with  `mkdir -p /home/$USER/milvus/conf`
2.affter docker 19.03,nvidia-docker2 packages are deprecated. maybe need change docker start command to `docker run -td --gpus all --name milvus -e "TZ=Asia/Shanghai" -p 19530:19530 -p 8080:8080 -v /home/$USER/milvus/db:/opt/milvus/db -v /home/$USER/milvus/conf:/opt/milvus/conf -v /home/$USER/milvus/logs:/opt/milvus/logs milvusdb/milvus:latest `

**Additional reference**
Provide any other reference docs or websites about your request.
https://github.com/NVIDIA/nvidia-docker

**Comment by jielinxu** [comment]
Fixed in #140
