### ISSUE TITLE
[ERROR] The cpu_cache_capacity parameter description is not accurate

### ISSUE THREAD

**Issue by yamasite** [milvus-io/docs#156]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Where is the error**
[https://milvus.io/docs/en/reference/milvus_config/](https://milvus.io/docs/en/reference/milvus_config/])

The cpu_cache_capacity parameter description is not accurate.

**How would you like to improve it**
We need to add more information. For example:

cpu_cache_capacity specifies the size of the CPU memory for caching search data. This parameter must be less than the total CPU memory size. It is recommended that you reserve part of the CPU memory for other operations.

gpu_cache_capacity specifies the size of the GPU memory for caching search data. This parameter must be less than the total GPU memory size.

**Comment by jielinxu** [comment]
Fixed in #163
