### ISSUE TITLE
[ERROR] I can't start milvus by using server_config_gpu.yaml. But I can start milvus by using server_config.yaml.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/docs#222]

**Comment by yamasite** [comment]
That's right. The yaml file should be renamed as server_config.yaml. Otherwise, Milvus cannot start. We will add this information to the documentation.

**Comment by yamasite** [comment]
Now the config files of the CPU version and the GPU version have the same filename. The error you reported has been fixed.
