### ISSUE TITLE
[ERROR]When I start milvus of cpu version, I can find nothing in /home/$USER/milvus/logs.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/docs#229]
When I start milvus of cpu version, I can find nothing in /home/$USER/milvus/logs. And I have created some tables.

**Comment by yamasite** [comment]
That might be caused by mapping errors. I tried to reproduce the problem but failed.

**Comment by jielinxu** [comment]
This issue is already solved. It occurs because the mapped path of log files in the docker run command and the path in the log files are inconsistent.
