### ISSUE TITLE
bad link

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/docs#507]
website: https://github.com/milvus-io/docs/blob/0.6.0/userguide/cpu_milvus_docker.md

broken link：
![image](https://user-images.githubusercontent.com/53512883/78260655-c445a500-7530-11ea-9507-f9e586d2961f.png)
![image](https://user-images.githubusercontent.com/53512883/78260681-ce67a380-7530-11ea-9fa5-96c7945bead1.png)

**Comment by xudalin0609** [comment]
the link was not timely updated on this doc,you can find it on chinese guide[https://github.com/milvus-io/docs/blob/master/site/zh-CN/guides/get_started/install_milvus/cpu_milvus_docker.md](url)

**Comment by PahudPlus** [comment]
@AmyYH  Please double check if this issue has been put to rest.

**Comment by AmyYH** [comment]
Please refer to the latest version v0.10.2:
https://github.com/milvus-io/docs/blob/master/v0.10.2/site/zh-CN/quick_start/install_milvus/milvus_docker-cpu.md
