### ISSUE TITLE
[ERROR] Install milvus on macOS: docker error mounts denied

### ISSUE THREAD

**Issue by yujuew** [milvus-io/docs#523]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Where is the error**
https://github.com/milvus-io/docs/blob/v0.8.0/site/en/guides/get_started/install_milvus/cpu_milvus_docker.md#install-milvus-on-macos

**How would you like to improve it**
In step 4, it seems like that the right volume path for macOS should be /Users/$USER/milvus/... instead of /home/$USER/milvus/...

**Screenshots**
![Docker Error: Mounts denied](https://user-images.githubusercontent.com/33749842/80299726-32e0f000-87c9-11ea-9d5d-ab2645bb0858.png)

After correcting
![Milvus Container runs correctly](https://user-images.githubusercontent.com/33749842/80299798-cd413380-87c9-11ea-8f7d-b89432f06c12.png)

**Comment by JinHai-CN** [comment]
Thank you for your comments, the document will be updated.

**Comment by PahudPlus** [comment]
The above-mentioned content has been removed already.
