### ISSUE TITLE
[ERROR] operational_faq.md link 404

### ISSUE THREAD

**Issue by nameczz** [milvus-io/docs#526]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Where is the error**
https://milvus.io/cn/docs/v0.8.0/faq/operational_faq.md
Milvus 对 collection 和 分区的数量有限制吗？
为什么 Milvus 返回 config check error 的错误？
two error link return 404 page

**How would you like to improve it**

**Screenshots**

**Comment by PahudPlus** [comment]
The issue has been fixed in 0.10.2
