### ISSUE TITLE
[ERROR] example.py is missing

### ISSUE THREAD

**Issue by hdoer** [milvus-io/docs#540]
**Where is the error**
I got the message "404: Not Found" when 
 I visit the page https://raw.githubusercontent.com/milvus-io/pymilvus/0.9.0/examples/example.py.
The URL was wrote in https://www.milvus.io/docs/v0.9.0/guides/get_started/example_code.md

In addition, I clicked on the link "example code." in the URL above. It took me to the example page but version is 0.8.0. I Run the example and got a error message "AttributeError: 'Milvus' object has no attribute 'ping'".

Then I searched in github and got the message "update example to remove ping case". The URL is https://github.com/milvus-io/pymilvus/commit/58c569bd9a5f8ded1c545221e7cbfb5463e66d40.

**How would you like to improve it**
Please update the doc "https://www.milvus.io/docs/v0.9.0/guides/get_started/example_code.md".

**Comment by PahudPlus** [comment]
Thanks hdoer for the findings. The wget link should be https://raw.githubusercontent.com/milvus-io/pymilvus/0.2.11/examples/example.py instead. 

0.2.11 is the version of the client SDK. It corresponds to the Milvus server version 0.9.0.

Will fix the issue shortly after. 

Many thanks.

**Comment by PahudPlus** [comment]
Issue fixed: https://github.com/milvus-io/docs/pull/542

**Comment by hdoer** [comment]
>Note: If you cannot use wget to download the example code, you can also create example.py and copy the [example code](https://github.com/milvus-io/pymilvus/blob/0.8.0/examples/example.py).

The link of "example code." in https://www.milvus.io/docs/v0.9.0/guides/get_started/example_code.md. should also be updated.
