### ISSUE TITLE
[QUESTION] Source code for sizing tool?

### ISSUE THREAD

**Issue by mausch** [milvus-io/docs#544]
https://milvus.io/tools/sizing is great, I love it.
I'd like to see how the calculations are made and maybe contribute to it by adding other indices or at least adding a link to the index reference docs https://milvus.io/docs/guides/index.md .
However I can't seem to find its source code in any repo in https://github.com/milvus-io , am I missing something?

Many thanks for all your hard work!

**Comment by shanghaikid** [comment]
Hi, the page is in our website repo,  it is based on gatsby, a react based static site generator. 

The page is here: 
https://github.com/milvus-io/www.milvus.io/blob/master/src/pages/tool-sizing.js 

Any questions are welcome.

**Comment by mausch** [comment]
Great, thanks!
