### ISSUE TITLE
[ERROR] Should use "call" instead of "invoke"

### ISSUE THREAD

**Issue by awkwardme** [milvus-io/docs#553]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Where is the error**
[Section using the wrong term](https://www.milvus.io/docs/v0.10.0/guides/troubleshoot.md#Index-building-methods)

**How would you like to improve it**
Better use "call" instead of "invoke" in this context.

**Screenshots**
N/A

**Comment by PahudPlus** [comment]
Fixed.
