### ISSUE TITLE
[QUESTION] How are these structural diagrams drawn?

### ISSUE THREAD

**Issue by DonYum** [milvus-io/docs#555]
The structural diagrams are very bueatiful, such as:
https://github.com/milvus-io/docs/blob/v0.9.1/assets/milvus_arch.png

Can you tell me what tools you use?
Thanks a lot.

BRs!

**Comment by PahudPlus** [comment]
Hi there Eric,

We are thrilled that you like it! It was drawn using keynote. 

Many thanks,
Milvus Developer Team

**Comment by DonYum** [comment]
Thx a lot!
BRs!
