### ISSUE TITLE
[ERROR] Misleading description for the CPU-only version?

### ISSUE THREAD

**Issue by matteo-grella** [milvus-io/docs#556]
According to [this](https://github.com/milvus-io/milvus/discussions/3802) discussion, I find [this](https://github.com/milvus-io/docs/blame/master/v0.10.2/site/en/about_milvus/milvus_distributions-cpu.md#L18) sentence on the website a bit misleading:

> CPU-only Milvus only supports searching after index building completes, and hence is applicable to static datasets.

On the other hand, if it is correct, it might be useful to add some clarification in the discussion above.

**Comment by PahudPlus** [comment]
Hi there Matteo,

I've updated [this page](https://www.milvus.io/docs/v0.10.3/milvus_distributions-cpu.md#floating):

-  CPU-only Milvus only supports using CPU to search or build index.
- GPU-enabled Milvus supports GPU acceleration for searching and index building: You can use CPU for searching and GPU for index building at the same time to improve query efficiency.

Hopefully this version clarifies a bit. 

Cheers,
Keith
