### ISSUE TITLE
Version 0.11.0 of the dashboard.json is not available.

### ISSUE THREAD

**Issue by wanzaiqidao** [milvus-io/docs#560]
Version 0.11.0 of the dashboard.json is not available. I use this configuration and see no data on the dashboard. It needs an update.

**Comment by PahudPlus** [comment]
> Version 0.11.0 of the dashboard.json is not available. I use this configuration and see no data on the dashboard. It needs an update.

Hi wanzaiqidao, v0.11.0 does not support Mishards and has been moved off the shelf. You can use v0.10.5 instead. We are currently working on refactoring Milvus. Do please stayed tuned. 

Cheers,
Keith
