### ISSUE TITLE
cannot download milvus 0.11.0 config file

### ISSUE THREAD

**Issue by HoangTienDuc** [milvus-io/docs#567]

**Comment by PahudPlus** [comment]
Hi there HoangTienDuc, 

Apologies for the late response. Milvus v0.11.0 is an experimental release, and is no longer maintained. You can try Milvus v1.1 from https://milvus.io/docs/v1.1.0/install_milvus.md, which is our LTS version. If you need scalar filtering, you have to wait for our Milvus v2.0, which is a Beta release and will be available by the end of June. 

Cheers,
Keith
