### ISSUE TITLE
[Suggestion] Add one more parameter on config files

### ISSUE THREAD

**Issue by JinHai-CN** [milvus-io/docs#75]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Is there anything that's missing or inappropriate in the docs? Please describe.**
One more parameter is added to milvus to control which tables will be loaded to memory at milvus startup.

**Describe your suggestion**
Please check with developer on the usage of this parameters

**Additional reference**
No

**Comment by jielinxu** [comment]
Got it. Will add it in the next release.

**Comment by jielinxu** [comment]
#78 Already added the parameter `preload_table` in branch 0.5.0.
