### ISSUE TITLE
[Suggestion] The Install Milvus topic should have a section for hardware requirements

### ISSUE THREAD

**Issue by yamasite** [milvus-io/docs#96]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Is there anything that's missing or inappropriate in the docs? Please describe.**
Hardware support information is missing in the [Install Milvus](https://milvus.io/docs/en/userguide/install_milvus/) topic. Users will find it difficult to determine whether they have the right hardware.

**Describe your suggestion**
We should add hardware support information to the [Install Milvus](https://milvus.io/docs/en/userguide/install_milvus/) topic.

**Comment by jielinxu** [comment]
Fixed in #97
